export const ACCOUNT_LOGIN = "ACCOUNT_LOGIN";
//export const ACCOUNT_LOGOUT = "ACCOUNT_LOGOUT";
export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
