# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('S', 'Student'), ('M', 'Mentor'), ('B', 'Both')], max_length=1)),
            ],
        ),
    ]
