# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20161119_1922'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTeste',
            new_name='User',
        ),
    ]
