# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 20:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_auto_20161119_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('estimated_time', models.DurationField()),
                ('importance', models.SmallIntegerField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2016, 11, 19, 20, 26, 6, 639746, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='user',
            name='level_of_education',
            field=models.CharField(choices=[('0', 'Nao frequentou'), ('1', 'Fundamental cursando'), ('2', 'Fundamental concluido'), ('3', 'Medio cursando'), ('4', 'Medio concluido'), ('5', 'Superior cursando'), ('6', 'Superior concluido'), ('7', 'Pos cursando'), ('8', 'Pos concluido')], default='3', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='&0k4f@', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('0', 'Estudante'), ('1', 'Educador'), ('2', 'Ambos')], max_length=1),
        ),
    ]
