# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 20:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_auto_20161119_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='estimated_time',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='importance',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2016, 11, 19, 20, 27, 43, 909207, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='&0k4f', max_length=30),
        ),
    ]
