# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 20:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_auto_20161119_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='estimated_time',
            field=models.DurationField(default=datetime.timedelta(0, 28800)),
        ),
        migrations.AddField(
            model_name='ticket',
            name='importance',
            field=models.SmallIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2016, 11, 19, 20, 33, 20, 578686, tzinfo=utc)),
        ),
    ]
